apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: busybox
    command:
    - sh
    - -c
    - /tools/goss
    volumeMounts:
    - name: goss
      mountPath: /tools
  initContainers:
  - name: download-goss
    image: busybox
    command:
    - sh
    - -c
    - wget https://github.com/goss-org/goss/releases/latest/download/goss-linux-amd64 -O /tools/goss; chmod +rx /tools/goss
    volumeMounts:
    - name: goss
      mountPath: /tools
  volumes:
  - name: goss
    emptyDir: {}
  restartPolicy: Never